# Linting and prettifying code on pull requests
name: CI - Lint

on:
  pull_request_target:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop

jobs:
  eslint:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.6
      - name: Upgrade npm
        run: npm install -g npm
      - run: npm install --quiet
      - name: Run ESLint
        run: npm run lint

  prettier:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.6
      - name: Check code format
        uses: creyD/prettier_action@v3.0
        with:
          dry: True
          only_changed: True
          prettier_options: --write **/*.{ts,tsx,js,jsx,md}
